- README.md
> Fix logo location

- lib/alcotest.ml
maybe there should be a boolean assert to check boolean values
> add boolean assert

- .merlin
> Remove uuseg from .merlin

- examples/bad.ml
- examples/simple.ml
- lib/alcotest.ml
> Fix typos in json output and in comment

- CHANGES.md
- src/alcotest.mli
> fix typo in documentation

- src/alcotest.ml
- src/alcotest.mli
> Add int32,int64,float testables

- src/alcotest.ml
- src/alcotest.mli
> Add arrays

- src/alcotest.ml
Checks if there is `_build` in the current dir. Dumps outputs in `_build/_tests` if so. Fixes #76.
> Detect _build and move output there

- src/alcotest.ml
- src/alcotest.mli
> Add the negation operator

- .travis.yml
- Makefile
- alcotest-lwt.opam
- lwt/alcotest_lwt.ml
- lwt/alcotest_lwt.mli
- lwt/jbuild
- src/alcotest.ml
- src/alcotest.mli
> Add an alcotest-lwt package

- src/alcotest.ml
- src/alcotest.mli
> Add Alcotest.failf

- alcotest-async.descr
- alcotest-lwt.descr
- alcotest.descr
This is useful when creating new releases.
> Add opam descriptions

- README.md
> Add words about extra arguments and lwt in README

- README.md
> Add a (partial) comparison between testing frameworks

- src/alcotest.mli
Fixes #163 
As suggested in the discussion, added some explanation to the documentation comment.
> Improve documentation of argv parameter

- README.md
- alcotest.opam
- src/alcotest.ml
- src/dune
This is a candidate solution for #156.
CC: @samoht
> Add support for executing subsets of tests via CLI

- src/alcotest.ml
- src/alcotest.mli
This cleans up https://github.com/mirage/irmin/pull/828, which was incorrectly formatted.
> Reformat with ocamlformat.0.10

- src/alcotest.ml
This fixes #173.
~~Currently based on #169 (unmerged).~~
> Remove uses of deprecated Pervasives.compare

- .travis.yml
~~This is currently based on #169 (unmerged).~~
> Add CI runner for OCaml 4.08

- test/e2e/failing/compact.expected
- test/e2e/failing/compact.ml
- test/e2e/failing/dune.inc
...which was previously untested.
> Add test of --compact output

- CHANGES.md
> Fix 1.0.1 changelog entry

- src/alcotest/cli.mli
This will be picked up in CI after https://github.com/ocurrent/ocaml-ci/pull/105 is merged.
> Fix ODoc warning

- .ocamlformat
- src/alcotest-lwt/alcotest_lwt.mli
- src/alcotest/alcotest.mli
- src/alcotest/cli.mli
- src/alcotest/core.mli
- src/alcotest/pp.mli
I find it difficult to do without this option now :stuck_out_tongue:
> Use OCamlformat option parse-docstrings

- src/alcotest/core.ml
- src/alcotest/utils.ml
- src/alcotest/utils.mli
Tiny refactor to move a function where it belongs.
> Move `mkdir_p` implementation to Utils

- CHANGES.md
- src/alcotest/core.ml
- test/e2e/alcotest/failing/dune.inc
- test/e2e/alcotest/failing/separator_testname.expected
- test/e2e/alcotest/failing/separator_testname.ml
- test/e2e/alcotest/failing/unicode_testname.expected
> Fix test-case name validation regex.

- src/alcotest/alcotest.ml
See https://github.com/mirage/alcotest/pull/242#issuecomment-631109239.
The test suite creates contention for these symlinks, so we were occasionally getting failures due to these race conditions. This just adds a few retries to each operation on failure.
> Mitigate race conditions in Unix platform implementation

- CHANGES.md
Corresponding `opam-repository` PR is: https://github.com/ocaml/opam-repository/pull/16806#event-3540082401.
> Release 1.2.0

- CHANGES.md
Corresponding `opam-repository` PR: https://github.com/ocaml/opam-repository/pull/16818
> Release 1.2.1

- .github/workflows/changelog-check.yml
... using a GitHub Actions script implemented by @emillon (https://github.com/ocaml-ppx/ocamlformat/blob/6c2524ba7cb737dda647176f47f155b4d74aa90f/.github/workflows/main.yml).
> Add a CI check for changelog entries

- CHANGES.md
Corresponding PR in `opam-repository`: https://github.com/ocaml/opam-repository/pull/17068.
> Prepare to release 1.2.2

- CHANGES.md
Corresponding `opam-repository` PR: https://github.com/ocaml/opam-repository/pull/17153.
> Prepare to release 1.2.3

- CHANGES.md
Corresponding `opam-repository` PR: https://github.com/ocaml/opam-repository/pull/18169.
> Prepare 1.3.0 release

- .ocamlformat
This is a preview of the not-yet-released ocamlformat.0.17.0, please wait until the package is published in opam to merge this PR.
> Preview: upgrade to ocamlformat.0.17.0

- CHANGES.md
Opam-repository PR: https://github.com/ocaml/opam-repository/pull/18509.
> Release 1.4.0

- src/alcotest-engine/cli.ml
- src/alcotest-engine/cli.mli
- src/alcotest-engine/cli_intf.ml
Based on https://github.com/mirage/alcotest/pull/306 for convenience.
> De-duplicate Cli module types

- .ocamlformat
- test/e2e/gen_dune_rules.ml
This is a preview of the not-yet-released `ocamlformat.0.19.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.
> [Preview] Upgrade to ocamlformat.0.19.0

- README.md
See https://github.com/mirage/alcotest/issues/319.
> Add a more prominent docs link to the README

- src/alcotest-engine/core.ml
- src/alcotest-engine/pp.ml
- src/alcotest/alcotest_stubs.c
(I dont think this requires a changelog entry)
> Minor patches: consistent naming and allocation in C stubs

- alcotest.opam
- dune-project
- src/alcotest/runtime.js
see https://github.com/ocsigen/js_of_ocaml/pull/1602
> Adapt jsoo runtime to new jsoo version
