mirage/alcotest

examples/bad.ml
lib/alcotest.ml
lib/alcotest.mli

Maybe we still want to keep a global counter for the number of errors ... not totally clear to me how we should use and compose these runs.

Remove global state

---

lib/alcotest.ml

otherwise the error message isn't actually displayed (on OCaml 4.02.2)
Previously a test I wrote failed with this rather uniformative output:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------
ASSERT same file kind
--------------------------------------------------------------------------------------------------------------------------------------------------------------
[failure] 
```
Now it fails with:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------
ASSERT same file kind
----------------------------------------------------------------------------------------------- …
```

Alcotest.check: flush formatter

---

lib/alcotest.ml

The first dashed line for a test case starts on the same line as the start event. This adds the newline to fix that.

add missing newline to verbose output

---

lib/alcotest.ml

The current output file contents are mostly useless in the case of `Alcotest`-generated error messages. Lots of colorful successful assertion messages are printed but the actual cause of test failure is omitted.
This patch causes error and exception messages to be printed to the output file when the output is active. It also uses a single open fd to the result file for both stdout and stderr in order to have the message streams co-operate regarding file offset.

Fix output file contents

---

lib/alcotest.ml

Without this fix, the `-o` option looks like:
---o=DIR (absent=./_tests/)
with it:
-o DIR (absent=./_tests/)

Fix typo in -o option specification

---

lib/alcotest.ml

Changed list TESTABLE to use the equality of the underlying element, which is necessary for cases when (=) does not work (e.g. Cstruct list)

Change list TESTABLE

---

lib/alcotest.ml

Before:
```
-------------------------------------------------------------------------------------
ASSERT blah
-------------------------------------------------------------------------------------
- : unit = ()
```
After:
```
-------------------------------------------------------------------------------------
ASSERT blah
-------------------------------------------------------------------------------------
Exception:
Alcotest.Check_error "Fail blah: expecting Not_found, got nothing.".
-------------------------------------------------------------------------------------
ASSERT blah
-------------------------------------------------------------------------------------
Exception:
Alcotest.Check_error
"Fail blah: expecting Not_found, got Invalid_argument(\\\"\\\").". …
```

Fix check_raises

---

lib/alcotest.ml
lib/alcotest.mli

Use pass to disregard components of data types you are testing. For example, if you want to test that a pair-valued function, but disregard its second component for the in the test, you can use the following:
```ocaml
Alcotest.(pair int pass)
```

pass: add a testable that always passes

---

lib/alcotest.ml

This happens if we supply an empty string as the first element of the test case tuple.

Fix index out of bounds from empty test doc string

---

Makefile
examples/bad.ml
examples/simple.ml

@samoht this works with ocaml 4.02 and 4.03, by using the (already required) Astring functions instead of the OCaml stdlib ones

revert ignoring warning 3, use Astring uppercase instead of String/Char

---

lib/alcotest.ml

Before, it tended to squash things together (e.g. `abc` instead of `[a; b; c]`), which made test failures hard to read.
Fixes #53.
Signed-off-by: Thomas Leonard <thomas.leonard@docker.com>

Print lists with Fmt.Dump.list

---

lib/alcotest.ml
lib/alcotest.mli

When testing a variant (e.g. `result`), you need to pass a test for the other option. Using `pass` there looks wrong.
Signed-off-by: Thomas Leonard <thomas.leonard@docker.com>

Add reject test that always fails

---

lib/alcotest.ml
lib/alcotest.mli

It's useful when you try to use `Cmdliner`in top of `Alcotest`.

Add an optionnal argument `arg`

---

src/alcotest.ml

Before, Alcotest would print differences like this:
[failure] Error foo: expecting Ok
(xxx,
xxx), got
Ok
(xxx xxx).
It's hard to compare them like this. Instead, start a new line for both
values.

Format "got" and "expected" values in the same way

---

src/alcotest.ml
src/alcotest.mli

Due to approximate nature of floats direct equality is rarely useful in practice. This PR adds a basic form approximate equality: "equal up to an absolute error".
There is one more step we can take to make testing floating point code with Alcotest a breeze: generalize `Alcotest.float` to support support relative error and "equal up to [ULP](](https://en.wikipedia.org/wiki/Unit_in_the_last_place))" via polymorphic variants, e.g.
```ocaml
Alcotest.float (`Ulp 1)
Alcotest.float (`Abs 1)
Alcotest.float (`Rel 1)
```
What do you think?

Allowed passing absolute error to Alcotest.float

---

src/alcotest.ml
src/alcotest.mli

This is breaking backward compatibility for a lot of packages as people seem to
like using `let test = ... in Alcotest.(check .... test ...)`

Partially revert ac7e79865a66d6926c03d3e3f25099dc5df395ff

---

lwt/alcotest_lwt.ml
lwt/alcotest_lwt.mli
src/alcotest.ml
src/alcotest.mli

This state parameter is built by looking at the CLI. Use `Alcotest.run_with_args`
to use this, as `Alcotest.run` will continue to pass `()` as test parameters.
Fix #93

Allow the test-case to take a state parameter as argument

---

src/alcotest.ml

This allows to use `float 0.` for exact equality. Fix #106

Use <= instead of < in float combinator

---

src/alcotest.ml

The redirect logic is still very hairy, but this looks like the minimal amount of changes needed to clarify that `-v` doesn't save the log results to a file, and thus should not display the log results from that (very possibly outdated) file.
Should address #97

Do not display outdated logs when using `-v`

---

src/alcotest.ml

This PR changes the behavior of Alcotest, so that without `--show-errors` and `--verbose`, if there are any failures, the first failure is printed to standard output.
In current Alcotest, if one test fails, Alcotest shows the failure. However, if multiple tests fail, they are written to some log, which is difficult to use. Standard output receives only a list of names of the
failed tests.
Also in current Alcotest, the `--show-errors` and `--verbose` flags cause all the failures to be printed to standard output. However, this can be overwhelming if a large number of tests fail. Worse, in a progressive test suite, the first failure is the most relevant, so it would be nice if it was printed last. Then, the interactive user wouldn't have to scroll up through the entire failure list to find …

Show one failure when multiple tests fail

---

README.md
src/alcotest.ml
src/alcotest.mli

Filtering testcases was scarcely documented (had to read the source code to find out the expected format): add an example to the README, and make --help more explicit that up to 2 arguments can be used for filtering (the name of the test, and the test case index).
Also fix a bug with error messages getting lost on exit: OCaml doesn't flush Format.stderr on exit, just Format.stdout, so we have to flush it ourselves.
The improved output compared to the old one looks like this:
```diff
--- old
+++ new
@@ -1,15 +1,19 @@
+ ./simple test test_set invalidnumber
+simple: TESTCASE argument: invalid value `invalidnumber', expected an integer
+Usage: simple test [OPTION]... [NAME] [TESTCASE]
+Try `simple test --help' or `simple --help' for more information.
Testing My first test.
+ echo '$?=' 1
$?= …
```

Improve documentation on test case filtering and flush error formatter on exit

---

.travis.yml
alcotest.opam
src/alcotest.ml
src/jbuild

#125 
--
This proposed change takes a dependency on `uuidm` to generate UUIDs. It extends the `alcotest` global state to hold a globally unique run ID. This ID is newly generated on each call into `run_with_args` and is displayed out to the user before running any tests. The output logs from the tests are then placed in this sub directory which itself is under the `-o` directory (or under the default test directory if this is not specified).
To test this change I pinned my local clone with the changes, built the test executable of another project and repeatedly manually invoked it. The output logs were subsequently generated in separate sub-directories corresponding to the ID of the run, as expected.
#135 
--
This was caused by `dune` altering the current working directory before running …

Creates a fresh log sub-directory on each run

---

src/alcotest.ml
src/dune

This is a fix for #140:
- hard-coded path separator "/" has been replaced by `Filename.dir_sep`
- `mkdir_p` now can deal with Windows absolute paths, containing drive letters, e.g., C:\
Tested on Windows 10 cygwin/mingw toolchain & Windows 10 WSL aka Bash for Windows (Ubuntu 18.04)
Default path shown by `test_runner --help` still looks broken, but this is only a cosmetic issue (probably needs more escaping for "\\")

fix output path for windows/cygwin

---

.travis.yml
CHANGES.md
src/alcotest.mli

Minor changes and update README:
- fix ocamldoc headings with latest odoc
- do not test on debian-unstable (moving target) and use
fedora there instead

release 0.8.5

---

src/alcotest.ml

This PR adds option `--silent` which will suppress output for all successful tests.
It contains two commits - one which removes an unused global mutable variable (quiet), and one to add option `--silent`
This addresses #146. 
I did not want this PR to be too intrusive, so there are some `if t.silent then ...` scattered around the code.  Also I would have preferred to not have the first two lines printed (see examples below), but these are printed before any command line arguments are parsed, and I did not want to change the current flow.
Example when all tests are successful:
```
$ dune exec drivers/yaml/test/unittest.exe -- --silent
Testing yaml.
This run has ID `E09E988F-081E-4894-A7CB-E2D3FCFB60A5`.
...............................................................
```
Example with one …

Add silent option

---

src/alcotest.ml

Our CI is particularly "good" at finding race conditions in unit tests today for some reason, latest victim is alcotest:
```
unittest.exe: internal error, uncaught exception:                                                                                                                  
Unix.Unix_error(Unix.EEXIST, "mkdir", "//builddir/build/BUILD/...../_build/default/test/fake/_build")
```
This is a TOCTOU race condition between checking that the directory does not exist and creating it. Avoid it by ignoring EEXIST on mkdir, if we get EEXIST then we lost the race condition and someone else has already created the directory, but that is fine: all we wanted is to ensure the directory exists in the first place.

alcotest: fix EEXIST on mkdir

---

examples/dune
examples/floats.ml
src/alcotest.ml

Until now some comparisons between edge-cases in floats were failing.
A test suite for floats has been added in `examples/` to easily compare the before and after.
Edit: Reflecting back on this, there might be reason to keep the standard behaviour, I'm open to suggestion on how to best keep both behaviours.

Add checks for infinity and NaN in float check

---

src/alcotest.ml

Test output directories: Create symlinks for each test suite, and a "latest" symlink.
- The "latest" symlink points to the last test executed. This is useful to quickly navigate to whichever directory contains failing tests.
- Additionally a symlink named after t.name (in turn named after argv[0] of the test executable) is created. This is useful when there are multiple test executables being compiled as part of a build chain.
- Also try to avoid creating world-writable directories and files by setting umask and changing explicit permissions to og-rwx. This is best-effort, but since OCaml doesn't provide adequate bindings to the Unix system calls it is hard to perform operations like deleting files and creating directories recursively without introducing TOCTOU race conditions that can be …

Test output dirs: Create symlinks for each test suite + "latest"

---

src/alcotest.ml

This is a candidate solution for #128.
Currently the test length is measured in CPU time rather than real time, leading to unintuitive output when running tests that are not CPU-bound (particularly Lwt tests). This changes the internals to measure time with `Unix.time` instead.
Original behaviour:
```
let () =
Alcotest.run "alcotest" [
("bar1", [ Alcotest.test_case "unix" `Quick (fun () -> Unix.sleep 1)]);
("foo1", [ Alcotest_lwt.test_case "lwt" `Quick (fun _ () -> Lwt_unix.sleep 1.)]);
]
Test Successful in 0.000s. 2 tests run.
```
New behaviour:
```
Test Successful in 2.000s. 2 tests run.
```

Report real time rather than system time

---

alcotest-async.opam
alcotest-lwt.opam
alcotest.opam
src/alcotest.ml
src/alcotest.mli
src/dune

also bump minimal ocaml to 4.03.0 (CI tests 4.04+ only :/); and require `= version` in alcotest-{lwt,async} packages

remove result dependency

---

README.md
src/alcotest.ml

This is a candidate solution for #160 and #115.
If any of the tests fail registration, Alcotest will search for any additional registration errors, print them to stderr, and then exit with code 1. Alcotest now also gives an error if a test name contains forward or backward slashes (as these names must be valid folder names -- see #115).
Original behaviour:
```
[ craigfe@carbon ] ~/t/alcotest
ᐅ dune exec test/main.exe
Error: "\239\129\173" is not a valid test label (it should be an ASCII string), skipping.
Testing alcotest.
This run has ID `CC560E17-DF73-485F-A026-EF15BAEBB9B1`.
[OK]                bar1                0   unix.
[OK]                foo1                0   lwt.
...                with/slash          0   name_with_slash/foo.main.exe: internal error, uncaught exception: …
```

Handle filenames with slashes correctly

---

.ocamlformat
async/alcotest_async.ml
async/alcotest_async.mli
dune-project
examples/bad/bad.ml
examples/floats.ml
examples/simple.ml
lwt/alcotest_lwt.ml
lwt/alcotest_lwt.mli
src/alcotest.ml
src/alcotest.mli

I suggest the use of ocamlformat 0.10, now that it has been released.
Big QOL improvement at the cost of a big diff.

dune build @fmt: upgrade to ocamlformat.0.10

---

README.md
examples/lwt/dune
examples/lwt/test.ml
examples/simple.ml

- Updates the `simple.ml` to match the example given in the README
- Adds an additional set of examples using Lwt. These will provide a useful point-of-reference for any future suggestions/improvements to the API

Add examples of Alcotest-lwt usage

---

README.md
async/alcotest_async.ml
async/alcotest_async.mli
examples/lwt/test.ml
lwt/alcotest_lwt.ml
lwt/alcotest_lwt.mli
src/alcotest.ml
src/alcotest.mli

This resolves #119 by parameterising the core testing logic on a concurrency monad. This allows `Alcotest_lwt` and `Alcotest_async` to provide `run` methods that return promises, rather than using `Lwt_main.run` and `Thread_safe.block_on_async_exn` internally. As discussed in #119, these scheduling methods present problems for Javascript/Mirage deployments.
This PR is currently not `ocamlformat`-ted to minimise the diff while it's under review.
- Standard `Alcotest` keeps the same API, with no changes.
- `Alcotest.run` can now no longer run `Alcotest_lwt` test cases, which must instead be passed to `Alcotest_lwt.run` (see [this diff](https://github.com/mirage/alcotest/compare/master...CraigFe:monad#diff-0f4ab61e93c78dfaac56b35c0c0ed0f5)). The asynchronous backends now provide an …

Generalise test logic on a concurrency monad

---

.travis.yml
appveyor.yml

It would be nice to have CI on multiple OSs, since we currently use the file system to store log outputs of tests.
Currently just experimenting with TravisCI multi-OS support; not intended for merging.

Add CI runners for OS X and Windows

---

dune-project
test/e2e/dune
test/e2e/expect_failure.ml
test/e2e/failing/dune
test/e2e/failing/dune.inc
test/e2e/failing/unicode_testname.expected
test/e2e/failing/unicode_testname.ml
test/e2e/gen_dune_rules.ml
test/e2e/passing/basic.expected
test/e2e/passing/basic.ml
test/e2e/passing/dune
test/e2e/passing/dune.inc
test/e2e/strip_randomness.ml

This initialises an end-to-end test suite that compares example executions against expected outputs. The process is driven by auto-generated `dune` files, allowing a workflow of `dune runtest` →  `dune promote`. 
Currently this does not allow for passing options to the executable under test, which would be a nice addition. For this, we could use extra `*.opt` files similarly to [how it's being done in OCamlformat](https://github.com/ocaml-ppx/ocamlformat/tree/master/test/passing). 
1. The `dune` action DSL has no way of negating the exit code of a command, so it's being done manually with a little script -- I might request this as a Dune feature...
1. It's necessary to sanitize the output of the tests to remove environment dependencies / randomness. Again, this is being done by an extra …

Initial end-to-end test suite

---

src/alcotest.ml

This fixes #170 and fixes #175 by adding checks for filepath collisions whenever a test is registered.
Also refactors the test registration / caching logic to a separate `Suite` module and simplifies the logic  somewhat. This module is a candidate for splitting to a separate file, but doing so would require moving the types somewhere else too.

Refactor test registration logic

---

src/alcotest.ml
test/e2e/failing/dune.inc
test/e2e/failing/exception_in_test.expected
test/e2e/failing/exception_in_test.ml
test/e2e/passing/and_exit_false.expected
test/e2e/passing/and_exit_false.ml
test/e2e/passing/and_exit_true.expected
test/e2e/passing/and_exit_true.ml
test/e2e/passing/check_basic.expected
test/e2e/passing/check_basic.ml
test/e2e/passing/dune.inc
test/e2e/passing/filter_name.expected
test/e2e/passing/filter_name.ml
test/e2e/passing/filter_name_regex.expected
test/e2e/passing/filter_name_regex.ml
test/e2e/passing/json_output.expected
test/e2e/passing/json_output.ml
test/e2e/passing/list_tests.expected
test/e2e/passing/list_tests.ml
test/e2e/passing/quick_only.expected
test/e2e/passing/quick_only.ml
test/e2e/passing/quick_only_regex.expected
test/e2e/passing/quick_only_regex.ml

Adds a load of additional end-to-end tests intended to verify the behavior of the command-line arguments (and the `testable` checks). This will ease future restructuring of the Cmdliner logic.

Add tests of CLI args and testables

---

src/cli/dune

Should have been deleted as part of commit
6c6a23a56bf953166435418e644aef1422e4e876.

Remove stray Alcotest_cli dune file

---

src/cli.ml

Fixes https://github.com/mirage/alcotest/issues/184.

Remove version number from test CLI

---

async/alcotest_async.mli
lwt/alcotest_lwt.mli
src/core.ml
src/core.mli

We do not need to break the API here

expose Alcotest.speed_level again (instead of Alcotest.Core.speed_level)

---

alcotest-async.opam
alcotest-lwt.opam
alcotest.opam

This directive results in failure when downgrading Dune versions, due to version-specific functionality in the Dune language. See https://github.com/ocaml/opam/issues/3850 for more details.

opam: remove the 'build' directive on dune dependency

---

test/e2e/gen_dune_rules.ml
test/e2e/passing/check_basic.ml

Fixes two minor issues preventing the CI from being able to test Alcotest core on OCaml 4.03.

Fix CI for OCaml 4.03

---

.ocamlformat
src/alcotest/cli.ml
src/alcotest/core.ml
src/alcotest/output.ml
src/alcotest/output.mli
src/alcotest/pp.ml
src/alcotest/pp.mli
src/alcotest/utils.ml
src/alcotest/utils.mli
test/e2e/failing/check_basic.expected
test/e2e/failing/check_basic.ml
test/e2e/failing/dune.inc
test/e2e/failing/exception_in_test.expected
test/e2e/failing/invalid_arg_in_test.expected
test/e2e/failing/invalid_arg_in_test.ml
test/e2e/gen_dune_rules.ml
test/e2e/passing/json_output.expected
test/e2e/passing/list_tests.expected
test/e2e/strip_randomness.ml

An assorted collection of improvements/refactorings aimed at extracting more logic from the `Core` module. Mostly consists of splitting out pretty-printers for the output values and keeping them separate from the `Core.t` type, which is currently very overloaded.

Refactor formatting logic

---

alcotest.opam
dune-project
examples/bad/dune
examples/lwt/dune
src/alcotest-async/dune
src/alcotest-lwt/dune
src/alcotest/dune

Reviving https://github.com/mirage/alcotest/pull/197 with a new explicit dependency on `stdlib-shims` to eliminate the blockers there.

Make transitive dependencies explicit in dune files

---

examples/lwt/test.ml
src/alcotest-async/alcotest_async.ml
src/alcotest-async/alcotest_async.mli
src/alcotest-lwt/alcotest_lwt.ml
src/alcotest-lwt/alcotest_lwt.mli

The original names for these (introduced by https://github.com/mirage/alcotest/pull/202) are embarrassingly unhelpful. New names as proposed by @aantron: https://github.com/mirage/alcotest/pull/167#issuecomment-518565934.

Rename test_case' functions to test_case_sync

---

CHANGES.md
examples/simple.ml
src/alcotest/cli.ml
src/alcotest/cli.mli
src/alcotest/core.ml
src/alcotest/core.mli
src/alcotest/pp.mli
test/e2e/failing/dune.inc
test/e2e/failing/tail_errors_limit.expected
test/e2e/failing/tail_errors_limit.ml
test/e2e/failing/tail_errors_unlimited.expected
test/e2e/failing/tail_errors_unlimited.ml

This implements what I suggested in https://github.com/mirage/alcotest/issues/199
The goal is to declutter the console output when a verbose test fails.
This implementation uses a fixed limit of 100 lines. I didn't add a test because I'm not sure how check for the expected output at minimal effort. Here's a simple test to see what happens:
```ocaml
let test_error_output () =
for i = 1 to 1000 do
Printf.printf "output line %i\n" i
done;
Alcotest.fail "This was supposed to fail."
```
When adding this test to `examples/simple.ml`, we get the following output:
```
$ cd _build/default/examples && ./simple.exe
Testing Utils.
This run has ID `80588429-621C-4BF9-8CD4-93D70A7BD0A9`.
[OK]                string-case              0   Lower case.
[OK]                string-case              1 …
```

Show at most 100 lines of output for a failed test.

---

CHANGES.md
src/alcotest/cli.ml

This offers an alternate way to specify color output, consistent with other options. See #207 . It just works. I don't think this needs a test since it's really just one call to an external function.

Add support for environment variable ALCOTEST_COLOR

---

.ocamlformat

- reformats the code to be compliant with OCamlformat v0.13.0
- updates the `.ocamlformat` file accordingly

Upgrade to OCamlformat v0.13.0

---

alcotest.opam
dune-project

Fixes https://github.com/mirage/alcotest/issues/218.

Tighten lower bound on Fmt for new result combinator

---

test/e2e/alcotest/failing/dune.inc
test/e2e/alcotest/failing/duplicate_test_names.expected
test/e2e/alcotest/failing/duplicate_test_names.ml
test/e2e/alcotest/failing/filter_all_tests.expected
test/e2e/alcotest/failing/filter_all_tests.ml
test/e2e/alcotest/failing/filter_all_tests.opts

This adds two tests of edge cases that were previously untested:
- a filter is passed via `test [NAME_REGEX] [TESTCASES]` that filters out all tests
- the suite contains duplicate test names (see https://github.com/mirage/alcotest/pull/176)

Test filtering and duplicate-checking logic

---

src/alcotest/cli.ml
test/e2e/alcotest/passing/cli_verbose.expected
test/e2e/alcotest/passing/cli_verbose.ml
test/e2e/alcotest/passing/cli_verbose.opts
test/e2e/alcotest/passing/dune.inc

This cleans up the option handling logic and documents the precedence order that is expected to hold. This avoids setting default values for e.g.  `--verbose` in both `core.ml` and `cli.ml`.
Also adds a test verifying that the `--verbose` CLI flag takes priority over the compile-time parameter.

Refactor and clarify processing of CLI flags

---

src/alcotest/alcotest.mli
src/alcotest/cli.ml
src/alcotest/cli.mli
src/alcotest/core.ml
src/alcotest/core.mli

Recent features have made the docs a bit too complex for newcomers (particularly monad parameterisation). This undoes the damage by reordering to present simplest concepts first and adding some explanation here and there.

Improve the documentation layout

---

CHANGES.md
src/alcotest/alcotest.ml
src/alcotest/core.ml
src/alcotest/utils.ml
src/alcotest/utils.mli
test/e2e/alcotest/failing/check_basic.expected
test/e2e/alcotest/failing/tail_errors_limit.expected
test/e2e/alcotest/failing/tail_errors_limit.ml
test/e2e/alcotest/failing/tail_errors_unlimited.expected
test/e2e/alcotest/passing/assert_and_verbose.expected
test/e2e/alcotest/passing/assert_and_verbose.ml
test/e2e/alcotest/passing/assert_not_printed.expected
test/e2e/alcotest/passing/assert_not_printed.ml
test/e2e/alcotest/passing/dune.inc
test/e2e/alcotest/passing/only_monadic_effects.expected
test/e2e/alcotest/passing/only_monadic_effects.ml

... by adding flushes in various places, being sure to flush internal `Format` buffers as well as those of the output channels.
This has the side-effect of ensuring that all `ASSERT` lines are captured in log files (when `--verbose` is not passed), which was previously not the case because of `Format` buffers being flushed after the redirection had stopped.
This supersedes the fix in https://github.com/mirage/alcotest/pull/215, which I now believe is taking the wrong approach: i.e. we should always print `ASSERTS` regardless of test failure, but should also be sure to capture them in the test logs correctly.

Fix interleaving of ASSERTs with other console output

---

test/e2e/alcotest/passing/dune.inc
test/e2e/alcotest/passing/verbose_newlines.expected
test/e2e/alcotest/passing/verbose_newlines.ml

This reproduces the bug detailed in https://github.com/mirage/alcotest/issues/225.
@samoht, this suggests that the `--verbose` flag is not in fact ignored. Can you give a minimal working example of the bug you were experiencing?

Add a reproduction of a bug with the --verbose flag

---

CHANGES.md
src/alcotest/alcotest.ml
src/alcotest/alcotest.mli
test/e2e/alcotest/passing/check_basic.expected
test/e2e/alcotest/passing/check_basic.ml

additional function `check_l` as the labeled arguments version of `check`

labeled version `check_l` of `check` exptected vs. actual

---

CHANGES.md
Makefile
src/alcotest-engine/test.ml
src/alcotest-engine/test.mli
test/e2e/alcotest/failing/check_basic.expected
test/e2e/alcotest/failing/check_basic.ml
test/e2e/alcotest/passing/check_basic.expected
test/e2e/alcotest/passing/check_basic.ml

Printing relies on `Format` escaping with `%S`, which I think is exactly what we want : plain text as long as it's printable, escaped otherwise.

Add Ocaml `bytes` testable.

---

.travis.yml
CHANGES.md
alcotest.opam
dune-project
src/alcotest-engine/cli.ml
src/alcotest-engine/test.ml
src/alcotest-engine/utils.ml
src/alcotest-engine/utils.mli
src/alcotest/alcotest.ml
test/e2e/alcotest-lwt/dune
test/e2e/alcotest-lwt/failing/dune
test/e2e/alcotest-lwt/passing/dune
test/e2e/alcotest/failing/dune
test/e2e/alcotest/inside-dune/color-default.expected
test/e2e/alcotest/inside-dune/color-overridden.expected
test/e2e/alcotest/inside-dune/dune
test/e2e/alcotest/inside-dune/test_color.ml
test/e2e/alcotest/passing/dune
test/e2e/dune
test/e2e/strip_randomness.ml

This changes the default value of the `--color` flag to `always` rather than `auto` when the `INSIDE_DUNE` variable is set.
As discussed before (see https://github.com/mirage/alcotest/issues/207 and https://github.com/ocaml/dune/issues/145), Alcotest output is not coloured by default if run via `dune runtest`, since Dune's buffering mechanism keeps the test process from having direct access to the terminal.
We now have the `ALCOTEST_COLOR` variable for experienced users to override this behaviour, but I suspect the better solution is to default to _always_ showing colours, so that new users are not surprised by this interaction. People who really don't want colours can still disable it with the environment variable or the command-line option.
Travis CI appears to filter out any ANSII …

Use coloured output by default when running INSIDE_DUNE

---

README.md
alcotest-help.txt
dune
test/e2e/strip_randomness.ml

Since the manpage is auto-generated from the `Cmdliner` specification, it's
easy to miss changes to its output in PRs. This adds a simple expect test to
make it more obvious what is changing.
It may also be useful as a quick reference for the supported options, so I've
linked to it from the README.

Document the manpage output

---

src/alcotest-engine/core.ml
src/alcotest-engine/pp.ml
src/alcotest-engine/utils.ml
src/alcotest-engine/utils.mli
test/e2e/alcotest/passing/unicode_testname.expected

We're currently using `String.length` in a few places to predict the width of
its printed representation. When the user-supplied string contains UTF-8
characters, this isn't sufficient. This PR gets the length in UTF-8 characters
instead.

Get string lengths in UTF-8 chars when appropriate

---

src/alcotest-engine/model.ml

We use `.` as a separator quite frequently in test and suite names, for
instance to refer to findlib names like `index.unix`. AFAIK, this character is
safe to use in filesystems, so we might as well allow it.

Allow period character to appear unescaped in test names

---

CHANGES.md
src/alcotest/dune

It was transitively working thanks to fmt.tty with the upstream fmt version but trying to use fmt's dune port failed.

Explicitly declare Alcotest's deps on fmt

---

CHANGES.md
src/alcotest-engine/core.ml
src/alcotest-engine/model.ml
src/alcotest-engine/pp.ml
src/alcotest-engine/pp.mli
test/e2e/alcotest/failing/dune.inc
test/e2e/alcotest/failing/duplicate_test_names.expected
test/e2e/alcotest/failing/empty_suite_name.expected
test/e2e/alcotest/failing/empty_suite_name.ml
test/e2e/alcotest/passing/dune.inc
test/e2e/alcotest/passing/empty_test_name.expected
test/e2e/alcotest/passing/empty_test_name.ml

Fix https://github.com/mirage/alcotest/issues/264.
This emits an error message when the user supplies an empty test suite name, which previously raised an uncaught exception due to trying to create a corresponding symlink with an empty name. As discussed in the linked issue, it seems better to avoid empty suite names altogether.
Also adds a test for the similar case for empty _test_ names, which isn't as problematic since we already append integers to these files on disk. In this case, I just chose to alter the filenames slightly to make sure that they don't start with a `.`.
Introduces a common `user_error` function for handling such cases.

Emit an error when the user supplies an empty suite name

---

.ocamlformat

- reformats the code to be compliant with OCamlformat v0.15.0
- updates the `.ocamlformat` file accordingly

Upgrade to OCamlformat v0.15.0

---

CHANGES.md
examples/bad/bad.ml
src/alcotest-engine/cli.ml

Fix https://github.com/mirage/alcotest/issues/270.
The logic that processes `Cmdliner` results was incorrect (again), resulting in failure to respect `~and_exit:false` when an exception is raised by the user code. In future, we should consolidate this parameter handling logic in one place (i.e. in `Core` when necessary) to avoid such bugs.
Also cleans up the `bad.ml` example slightly, which was a bit hard to read before.

Fix handling of `~and_exit` parameter when running via CLI functor

---

alcotest-async.opam
alcotest-lwt.opam
alcotest-mirage.opam
dune-project
examples/bad/dune
examples/dune
src/alcotest-engine/cli.ml
test/e2e/alcotest/failing/dune
test/e2e/alcotest/passing/dune

This only works because `exit_status_of_result` currently ignores the value passed, which is probably a bad idea.
See https://github.com/dbuenzli/cmdliner/pull/124.

Don't pass `unit_m` to `Term.exit_status_of_result`

---

.ocamlformat
src/alcotest-engine/cli.ml
src/alcotest-engine/core.ml
src/alcotest-engine/pp.ml
src/alcotest-engine/utils.ml
src/alcotest/alcotest.ml

Hi, this pull-request is a preview of the soon to be released ocamlformat.0.16.0. The main change in the diff is that `indicate-multiline-delimiters` option has now be switched to `no` on the conventional profile to improve consistency and minimize the diffs in the future.
Let me now if you notice any regressions.

Preview of ocamlformat.0.16.0

---

CHANGES.md
src/alcotest/alcotest.ml
test/e2e/alcotest-lwt/passing/cli_options.expected
test/e2e/alcotest/passing/json_output.expected
test/e2e/strip_randomness.ml

We print the duration of test suites to millisecond precision, so we should be using a time source with at least that precision.
It'd be more correct to use `mtime`, but this [doesn't yet support Windows](https://github.com/dbuenzli/mtime/issues/2).

Use Unix.gettimeofday rather than Unix.time

---

CHANGES.md
src/alcotest-engine/test.ml
src/alcotest-engine/test.mli
test/e2e/alcotest/failing/check_basic.expected
test/e2e/alcotest/failing/check_basic.ml
test/e2e/alcotest/passing/check_basic.expected
test/e2e/alcotest/passing/check_basic.ml

Add a new testable `triple` that is very similar to `pair`.
Resolves #288.

Add triple testable for 3-elements tuple

---

CHANGES.md
src/alcotest-engine/test.ml
src/alcotest-engine/test.mli
src/alcotest/alcotest.mli
test/e2e/alcotest/failing/check_located.expected
test/e2e/alcotest/failing/check_located.ml
test/e2e/alcotest/failing/dune.inc

This location information is used to give more helpful error messages if the assertions fail.
CC: @mefyl.

Add optional location information on test assertion functions

---

src/alcotest-engine/test.ml
test/e2e/alcotest/failing/outside_runner.ml

This ensures that passing assertions with an empty message are silent, which is probably the correct behaviour.

Don't print empty assertions

---

alcotest.opam
dune-project

The Ocaml CI sometimes fails with `Unbound value Cmdliner.Arg.conv`, which was introduced in version 1.0.0

alcotest.opam: add lower bound on cmdliner

---

src/alcotest-engine/core.ml
src/alcotest-engine/log_trap.ml
src/alcotest-engine/log_trap.mli
src/alcotest-engine/log_trap_intf.ml
src/alcotest-engine/model.ml
src/alcotest-engine/monad.ml
src/alcotest-engine/monad_intf.ml
src/alcotest-engine/platform.ml
src/alcotest-engine/pp.ml
src/alcotest-engine/pp_intf.ml
src/alcotest-engine/utils.ml
src/alcotest-engine/utils.mli
src/alcotest-mirage/alcotest_mirage.ml
src/alcotest/alcotest.ml
src/alcotest/dune

Pulls out a `Log_trap` component for capturing test logs in files.
This is another chunk of refactoring extracted from https://github.com/mirage/alcotest/pull/294, which requires some more complicated redirection logic.

Extract Log_trap abstraction and cleanup log handling

---

CHANGES.md
alcotest.opam
dune-project
src/alcotest-engine/core.ml
src/alcotest-engine/dune
src/alcotest-engine/log_trap_intf.ml
test/e2e/strip_randomness.ml

Currently we use `uuidm` for generating test IDs. These seem a bit unnecessarily long to display / view when debugging: 8 alphanumeric characters is already enough for 3 trillion unique IDs, so I've gone with that.

Use shorter random IDs for test runs

---

CHANGES.md
src/alcotest-engine/cli.ml
src/alcotest-engine/config.ml
src/alcotest-engine/config_intf.ml
src/alcotest-engine/core.ml
src/alcotest-engine/core_intf.ml
src/alcotest-stdlib-ext/alcotest_stdlib_ext.ml
src/alcotest-stdlib-ext/alcotest_stdlib_ext.mli

The existing type of this argument is very obscure – and was added purely to
keep the CLI in correspondence with the runtime config – and so it's seen no
use in the Opam repository. This changes the type to be more sensible, in a way
that simplifies the V2 PR.

Change the `~filter` test selector to be a predicate

---

.github/workflows/changelog-check.yml
CONTRIBUTING.md
README.md

Already done in GitHub, but there are some bits in the repository itself to tweak.

Rename the default branch to 'main'

---

alcotest-async.opam
alcotest-js.opam
alcotest-lwt.opam
alcotest-mirage.opam
alcotest.opam
dune-project

This release is incompatible with Alcotest for now.
Temporarily solution to fix the CI until https://github.com/mirage/alcotest/pull/339 can be merged.

Constrain packages to avoid Cmdliner.1.1.0

---

src/alcotest-engine/core_intf.ml

Document filter parameter

---

.ocamlformat
alcotest-async.opam
alcotest-lwt.opam
alcotest-mirage.opam
alcotest.opam
dune-project

`alcotest >= 1.5.0 → fmt >= 0.8.7 → ocaml >= 4.05.0`
Also set OCamlFormat parser to OCaml 4.05 to make sure it doesn't reformat using newer syntax.

Correctly lower-bound on OCaml 4.05

---

README.md

Fixes https://github.com/mirage/alcotest/issues/338.

Fix link to the API documentation in the README

---

CHANGES.md
src/alcotest-engine/log_trap.ml

Do not use symlink when writing and reading log files.

---

src/alcotest/dune

Silences the alert proposed in ocaml/ocaml#11198, but this PR can be merged regardless.

Add missing dependency on Unix

---

.github/workflows/build.yml
CHANGES.md
alcotest-async.opam
dune-project
src/alcotest-async/alcotest_async.ml
src/alcotest-async/alcotest_async_intf.ml
src/alcotest-async/dune
test/e2e/alcotest/failing/unknown_option-js.expected

Upgrade to async v0.15.
It might be undesirable but includes `cmdliner >= "1.1.0"` update.
PR submitted in hopes it might save some time for whom it may concern.

Upgrade to async v0.15

---

CHANGES.md
src/alcotest-engine/cli.ml
src/alcotest-engine/config.ml
src/alcotest-engine/config_intf.ml
src/alcotest-engine/core.ml
src/alcotest-engine/core_intf.ml
test/e2e/dune

This PR attempts to do simple integration from Alcotest to CI systems. For now, Alcotest detects the CI system using the `CI`, `GITHUB_ACTIONS`, or `OCAMLCI` environment variables. As a first showcase of what we can do, when detecting GitHub Actions it will output annotations allowing to fold/unfold a test suite in the web interface. When detecting it's running in CI, Alcotest will also enable the show_errors modes (this can be overridden via the API) so that all failing tests are displayed in the CI (otherwise users would have to fix the failing test, push, and so on, to see the other errors).
I plan to expand the features if this PR is well received.

Basic CI integration

---

CHANGES.md
src/alcotest-engine/callsite_loc.412.ml
src/alcotest-engine/cli.ml
src/alcotest-engine/dune
src/alcotest-engine/test.ml
src/alcotest-engine/test.mli
test/e2e/alcotest/source_code_position/dune
test/e2e/alcotest/source_code_position/pre-4.12.expected
test/e2e/alcotest/source_code_position/test_source_code_position.ml
test/e2e/alcotest/source_code_position/with-position.expected
test/e2e/alcotest/source_code_position/without-position.expected
test/e2e/dune

This is an attempt of automatically discover the location of calls to `Alcotest.check`, in order to not force the user to pass `~here` or `~pos` arguments. It uses `Printexc.get_callstack`. It's an early attempt that is fragile and requires OCaml 4.11.
The test need to end with the unit value in order to prevent the compiler from optimizing the last call to a tail-call, erasing the location in the process. Is there a way to change Alcotest' code so that this optimization doesn't happen?
A more advanced attempt should probably walk the call stack to find recognizable enclosing functions calls, add regression testing, and make it work (or default to no-op) on pre-4.11. I don't know whether the code is efficient enough.
Try it out with
```shell
dune exec --display=quiet -- …
```

Best-effort automatic reporting of the location of `Alcotest.check`

---

examples/bad/dune
examples/dune
test/e2e/alcotest-lwt/failing/dune.inc
test/e2e/alcotest-lwt/passing/dune.inc
test/e2e/alcotest/failing/dune.inc
test/e2e/alcotest/passing/dune.inc
test/e2e/gen_dune_rules.ml
test/e2e/strip_randomness.ml

Patch applied in Debian, so that alcotest's build and tests pass on all Debian architectures.

Fix compilation on bytecode architectures

---

src/alcotest-engine/core.ml
src/alcotest-engine/core_intf.ml
src/alcotest-engine/test.ml
src/alcotest-engine/test.mli
test/e2e/alcotest/passing/dune.inc
test/e2e/alcotest/passing/skip_in_test.expected
test/e2e/alcotest/passing/skip_in_test.ml

This is useful when you want to perform logic to check whether or not some test case can run in the current environment.
~~~ocaml
let test_only_on_windows () =
if Sys.os_type <> "Win32" then Alcotest.skip () else ();
(* actual test code *)
~~~

Allow skipping a test case from inside the test case

---

CHANGES.md
src/alcotest/alcotest_stubs.c

`unistd.h` is not present in Windows SDK (MSVC) and usually unnecessary.
Before:
```
========= [TROUBLESHOOTING] alcotest-3480-337052.out ===========
[alcotest-3480-337052.out] File "src/alcotest/dune", line 6, characters 9-23:
[alcotest-3480-337052.out] 6 |   (names alcotest_stubs))
[alcotest-3480-337052.out]              ^^^^^^^^^^^^^^
[alcotest-3480-337052.out] (cd _build/default/src/alcotest && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\cl.exe" -nologo -O2 -Gy- -MD -D_CRT_SECURE_NO_DEPRECATE -nologo -O2 -Gy- -MD -I D:/.opam/dkml/lib/ocaml -I D:\.opam\dkml\lib\astring -I D:\.opam\dkml\lib\fmt -I ../alcotest-engine /Foalcotest_stubs.obj -c alcotest_stubs.c)
[alcotest-3480-337052.out] alcotest_stubs.c …
```

alcotest_stubs.c compile with MSVC

---

README.md

These blocks are not shell scripts, but rather the shell session in a terminal. This syntax highlighting change reflects that.
To see it rendered as a preview, check the branch @ https://github.com/toastal/alcotest/blob/sh-session/README.md

syntax highlighting: shell → sh-session

---

CHANGES.md
src/alcotest-engine/test.ml
src/alcotest-engine/test.mli

proposal for issue 88: https://github.com/mirage/alcotest/issues/88

added match_raises a generalized version of check_raises

---

src/alcotest-engine/test.ml

For consistency and maybe better formatting too.

Use `Fmt.exn` instead of `Printexc.to_string`

---

alcotest-async.opam
alcotest-help.txt
alcotest-js.opam
alcotest-lwt.opam
alcotest-mirage.opam
alcotest.opam
dune-project

Cmdliner 1.2.0 provides Windows and help fixes.
It requires at least OCaml 4.08.

Bump to OCaml 4.08 and cmdliner 1.2.0

---

.github/workflows/build.yml
CHANGES.md
alcotest-async.opam
dune-project
src/alcotest-async/alcotest_async.ml
src/alcotest-async/alcotest_async_intf.ml
src/alcotest-async/dune

Fixes deprecation against core_unix.time_unix and bumps the OCaml version to 4.14.

Update JaneStreet core and async.

---

CHANGES.md
alcotest-help.txt
src/alcotest-engine/cli.ml
src/alcotest-stdlib-ext/alcotest_stdlib_ext.ml
src/alcotest-stdlib-ext/alcotest_stdlib_ext.mli
src/alcotest/alcotest.ml
src/alcotest/alcotest_stubs.c
test/e2e/dune

- Fix division by zero when size of the terminal is incorrectly reported as zero. (fix #356, #381, @MisterDA)
- Enable terminal size reporting on macOS and Windows. Also report the terminal size even when the test is run buffered by Dune.
(#381, @MisterDA)
- Allow overriding the number of columns with `ALCOTEST_COLUMNS` env var. (#322, #381, @MisterDA)
My intent was to use a bigger default than 80 columns when the CI is detected. Sadly, this would seem to require too big of a refactoring to communicate the default size to the `Pp` module, which is also why I haven't made the number of columns configurable programmatically, and exposed it only via an environment variable to fix reproducibility issues for the Unix platform.
Oddly enough, communicating the bounds to the `Format` module with …

Fix reporting terminal dimensions

---

CHANGES.md
src/alcotest/alcotest_stubs.c

If stdout is redirected on Windows, the dimensions of the terminal won't be correctly retrieved. Open the console instead, using the special filename `CONOUT$`, and ask the dimensions of this handle. Keep a fallback to stdout if the console can't be opened, because you can never be too cautious with this OS.
(this is akin to opening `/dev/tty` on Unix).
https://learn.microsoft.com/en-us/windows/console/console-handles

Open Windows console handle to retreive dimensions

---

test/e2e/strip_randomness.ml

The backtrace format changed in 5.2.
Otherwise `dune test` fails with:
```
#=== ERROR while compiling alcotest.1.7.0 =====================================#
```

Fix alcotest's own tests when using OCaml 5.2

---

CHANGES.md
alcotest-help.txt
src/alcotest-engine/cli.ml
src/alcotest-engine/config.ml
src/alcotest-engine/config_intf.ml

In light of recent discussions (see #394 #395), I think that simply using the `CI` environment variables to enable the `show_errors` behavior is sufficient, if there's nothing more to do to integrate the CI with Alcotest.
Turns out, we were already doing that with the `` `Unkown `` variant.
AppVeyor uses `CI=True` (capitalized), support that too. Couldn't find if Jenkins defines a specific variable.

Don't detect ocaml-ci specifically, improve CI detection

---

CHANGES.md
src/alcotest-engine/test.ml
src/alcotest-engine/test.mli

This PR adds:
- `seq` (to produces `'a Seq.t testable`) Because the `Seq.t` type has become very common in the standard library
- `contramap` which allows you to go from an `'a testable` to a `'b testable` giving a function from `b -> 'a` (because a testable is a contravariant functor). I have often found the function useful for implementing testables _quickly_ when there is a trivial transformation.

testable for seq and contramap (for testable)

---

src/alcotest/runtime.js

It's deprecated and will result in a warning with the next release of jsoo

no longer rely on joo_global_object

---

CHANGES.md
src/alcotest-engine/test.ml
src/alcotest-engine/test.mli
test/e2e/alcotest/passing/dune.inc
test/e2e/alcotest/passing/match_raises-js.expected
test/e2e/alcotest/passing/match_raises.expected
test/e2e/alcotest/passing/match_raises.ml

I don't know whether breaking behaviour is acceptable or not, opening to receive feedback.
I can always drop the commit with the breaking change and keep the one documenting current behaviour, suggestions on how to deal with this is welcome.
Fixes #418

[Breaking] Change match_raises to be more intuitive 

---

CHANGES.md
src/alcotest-engine/core.ml
src/alcotest-engine/core_intf.ml
src/alcotest-engine/test.ml

engine: expose skip exception
